package com.publicwelfareplatform.dao;

import com.publicwelfareplatform.model.entity.TB_USERS;

public interface TB_USERSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    int insert(TB_USERS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    int insertSelective(TB_USERS record);
}