package com.publicwelfareplatform.model.entity;

public class TB_USERS {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.Id
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.name
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.age
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.sex
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.adders
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private String adders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.job
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    private String job;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.Id
     *
     * @return the value of TB_USERS.Id
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.Id
     *
     * @param id the value for TB_USERS.Id
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.name
     *
     * @return the value of TB_USERS.name
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.name
     *
     * @param name the value for TB_USERS.name
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.age
     *
     * @return the value of TB_USERS.age
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.age
     *
     * @param age the value for TB_USERS.age
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.sex
     *
     * @return the value of TB_USERS.sex
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.sex
     *
     * @param sex the value for TB_USERS.sex
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.adders
     *
     * @return the value of TB_USERS.adders
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public String getAdders() {
        return adders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.adders
     *
     * @param adders the value for TB_USERS.adders
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setAdders(String adders) {
        this.adders = adders == null ? null : adders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.job
     *
     * @return the value of TB_USERS.job
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.job
     *
     * @param job the value for TB_USERS.job
     *
     * @mbggenerated Sun Feb 11 17:44:03 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }
}